[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "supabase/functions"

# Form handling configuration
[[forms]]
  name = "contact"

[[forms]]
  name = "contact-detailed"

# Email notifications for form submissions
[form]
  # Send notification emails to your address
  [form.settings]
    # This will send form submissions to your email
    to = "info@wolkenbunker.de"
    subject = "Neue Kontaktanfrage von WolkenBunker Website"

# Redirects for SEO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawler*", "*spider*", "*Googlebot*", "*Bingbot*", "*facebookexternalhit*", "*Twitterbot*", "*LinkedInBot*", "*SEOkicks*", "*seobility*", "*Seobility*"]}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.google.com https://www.gstatic.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co https://www.google.com https://www.gstatic.com https://www.googletagmanager.com; frame-src https://www.google.com https://recaptcha.google.com https://www.recaptcha.net; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"